maincc:main.o compress.o pack.o  hfman.o
	g++ pack.o compress.o main.o  hfman.o -o compress_win
main.o:main.cpp
	g++ -c main.cpp
pack.o:pack.cpp
	g++ -c pack.cpp
compress:compress.cpp
	g++ -c compress.cpp
hfman:hfman.cpp
	g++ -c hfman.cpp

#maincc:main.o compress.o pack.o debugg.o\
	g++ pack.o compress.o main.o  debugg.o -o compress_debug_co\
main.o:main.cpp\
	g++ -c main.cpp\
pack.o:pack.cpp\
	g++ -c pack.cpp\
compress:compress.cpp\
	g++ -c compress.cpp\
debugg:debugg.cpp\
	g++ -c debugg.cpp\